development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://djuldenisowwgl:T973o7NjIciq8ZnsGveoapWWB5@ec2-54-225-64-254.compute-1.amazonaws.com:5432/dfc9bbmof29t0d
